---
- name: Create Wings service file
  ansible.builtin.template:
    src: templates/wings.service.j2
    dest: /etc/systemd/system/wings.service
    owner: root
    group: root
    mode: "0644"

- name: Enable Wings at boot
  ansible.builtin.systemd_service:
    name: wings
    enabled: true
    state: restarted
